import { afterAll,beforeAll,describe,expect,it } from 'vitest'; import supertest from 'supertest'; import { sql } from 'kysely'; import { createApp } from '../app.js'; import { signAccessToken } from '../auth/tokens.js'; import { createDatabase,destroyDatabase,getDatabase } from '../db/database.js'; import { createPool,destroyPool } from '../db/pool.js';
let app:ReturnType<typeof createApp>; let firstToken:string; let secondToken:string; let firstUser:string; let secondUser:string; let addressId:string;
beforeAll(async()=>{createDatabase(createPool());const db=getDatabase();await sql`DELETE FROM customer_behavior_events`.execute(db);await sql`DELETE FROM customer_preferences`.execute(db);await sql`DELETE FROM customer_addresses`.execute(db);await sql`DELETE FROM user_roles`.execute(db);await sql`DELETE FROM refresh_tokens`.execute(db);await sql`DELETE FROM users WHERE email IN ('customer-data-one@test.com','customer-data-two@test.com')`.execute(db);const make=async(email:string)=>{const u=await sql<{id:string}>`INSERT INTO users(email,password_hash,created_at,updated_at) VALUES(${email},'unused',now(),now()) RETURNING id`.execute(db);return {id:u.rows[0]!.id,token:signAccessToken(u.rows[0]!.id,email)};};const one=await make('customer-data-one@test.com');const two=await make('customer-data-two@test.com');firstUser=one.id;secondUser=two.id;firstToken=one.token;secondToken=two.token;app=createApp();});
afterAll(async()=>{const db=getDatabase();await sql`DELETE FROM customer_behavior_events WHERE user_id IN (${firstUser},${secondUser})`.execute(db);await sql`DELETE FROM customer_preferences WHERE user_id IN (${firstUser},${secondUser})`.execute(db);await sql`DELETE FROM customer_addresses WHERE user_id IN (${firstUser},${secondUser})`.execute(db);await sql`DELETE FROM users WHERE id IN (${firstUser},${secondUser})`.execute(db);await destroyDatabase();await destroyPool();});
describe('customer-owned data',()=>{
it('requires authentication and isolates saved addresses',async()=>{await supertest(app).get('/account/addresses').expect(401);const created=await supertest(app).post('/account/addresses').set('Authorization',`Bearer ${firstToken}`).send({label:'Home',recipientName:'Asha Sen',addressLine1:'12 Park Street',city:'Kolkata',state:'West Bengal',postalCode:'700016',isDefault:true}).expect(201);addressId=(created.body as {id:string}).id;const first=await supertest(app).get('/account/addresses').set('Authorization',`Bearer ${firstToken}`).expect(200);expect(first.body as unknown[]).toHaveLength(1);const second=await supertest(app).get('/account/addresses').set('Authorization',`Bearer ${secondToken}`).expect(200);expect(second.body as unknown[]).toHaveLength(0);await supertest(app).patch(`/account/addresses/${addressId}`).set('Authorization',`Bearer ${secondToken}`).send({label:'Stolen'}).expect(404);await supertest(app).delete(`/account/addresses/${addressId}`).set('Authorization',`Bearer ${secondToken}`).expect(404);});
it('isolates preference profiles',async()=>{await supertest(app).put('/account/preferences').set('Authorization',`Bearer ${firstToken}`).send({audiences:['women'],preferredColours:['maroon'],sizePreferences:{topwear:'M'},personalizationConsent:true}).expect(200);const first=await supertest(app).get('/account/preferences').set('Authorization',`Bearer ${firstToken}`).expect(200);expect(first.body).toEqual(expect.objectContaining({audiences:['women'],preferredColours:['maroon'],personalizationConsent:true}));const second=await supertest(app).get('/account/preferences').set('Authorization',`Bearer ${secondToken}`).expect(200);expect(second.body).toEqual(expect.objectContaining({audiences:[],personalizationConsent:false}));});
it('captures behavior only with explicit consent',async()=>{await supertest(app).post('/account/behavior').set('Authorization',`Bearer ${secondToken}`).send({eventType:'search',searchQuery:'linen kurta'}).expect(403);await supertest(app).post('/account/behavior').set('Authorization',`Bearer ${firstToken}`).send({eventType:'search',searchQuery:'linen kurta'}).expect(201);const rows=await getDatabase().selectFrom('customer_behavior_events').select(['user_id','search_query']).execute();expect(rows).toEqual([{user_id:firstUser,search_query:'linen kurta'}]);});
it('maintains one default address per customer',async()=>{await supertest(app).post('/account/addresses').set('Authorization',`Bearer ${firstToken}`).send({label:'Office',recipientName:'Asha Sen',addressLine1:'4 Camac Street',city:'Kolkata',state:'West Bengal',postalCode:'700017',isDefault:true}).expect(201);const rows=await supertest(app).get('/account/addresses').set('Authorization',`Bearer ${firstToken}`).expect(200);expect((rows.body as Array<{isDefault:boolean}>).filter((item)=>item.isDefault)).toHaveLength(1);});
});
