import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import supertest from 'supertest';
import { sql } from 'kysely';
import { createApp } from '../app.js';
import { signAccessToken } from '../auth/tokens.js';
import { createDatabase, destroyDatabase, getDatabase } from '../db/database.js';
import { createPool, destroyPool } from '../db/pool.js';
let app: ReturnType<typeof createApp>; let readToken: string; let writeToken: string; let writeUserId: string; let firstProduct: string; let secondProduct: string;
beforeAll(async () => {
  createDatabase(createPool()); const db = getDatabase(); await sql`DELETE FROM recommendation_rule_products`.execute(db); await sql`DELETE FROM recommendation_rules`.execute(db); await sql`DELETE FROM audit_log`.execute(db); await sql`DELETE FROM user_roles`.execute(db); await sql`DELETE FROM refresh_tokens`.execute(db); await sql`DELETE FROM users`.execute(db);
  const category = await sql<{ id: string }>`INSERT INTO categories (name,slug,created_at,updated_at) VALUES ('Recommendation Test','recommendation-test',now(),now()) ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name RETURNING id`.execute(db);
  await sql`DELETE FROM products WHERE slug IN ('recommendation-one','recommendation-two')`.execute(db);
  const one = await sql<{ id: string }>`INSERT INTO products (name,slug,status,category_id,created_at,updated_at) VALUES ('Recommendation One','recommendation-one','active',${category.rows[0]!.id},now(),now()) RETURNING id`.execute(db); const two = await sql<{ id: string }>`INSERT INTO products (name,slug,status,category_id,created_at,updated_at) VALUES ('Recommendation Two','recommendation-two','active',${category.rows[0]!.id},now(),now()) RETURNING id`.execute(db); firstProduct = one.rows[0]!.id; secondProduct = two.rows[0]!.id;
  const roles = await db.selectFrom('roles').selectAll().execute(); const make = async (email: string, role: string) => { const user = await sql<{ id: string }>`INSERT INTO users (email,password_hash,created_at,updated_at) VALUES (${email},'unused',now(),now()) RETURNING id`.execute(db); await sql`INSERT INTO user_roles (user_id,role_id,created_at) VALUES (${user.rows[0]!.id},${roles.find((item) => item.name === role)!.id},now())`.execute(db); return {id:user.rows[0]!.id,token:signAccessToken(user.rows[0]!.id,email)}; }; const reader=await make('recommendation-read@test.com','backend_read');const writer=await make('recommendation-write@test.com','backend_write');readToken=reader.token;writeToken=writer.token;writeUserId=writer.id;app = createApp();
});
afterAll(async () => { const db = getDatabase(); await sql`DELETE FROM recommendation_rule_products`.execute(db); await sql`DELETE FROM recommendation_rules`.execute(db); await sql`DELETE FROM audit_log`.execute(db); await sql`DELETE FROM user_roles`.execute(db); await sql`DELETE FROM users`.execute(db); await sql`DELETE FROM products WHERE id IN (${firstProduct},${secondProduct})`.execute(db); await sql`DELETE FROM categories WHERE slug='recommendation-test'`.execute(db); await destroyDatabase(); await destroyPool(); });
describe('recommendation rules', () => {
  it('enforces roles and strategy validation', async () => { await supertest(app).get('/admin/recommendation-rules').expect(401); await supertest(app).get('/admin/recommendation-rules').set('Authorization',`Bearer ${readToken}`).expect(200); await supertest(app).post('/admin/recommendation-rules').set('Authorization',`Bearer ${readToken}`).send({}).expect(403); await supertest(app).post('/admin/recommendation-rules').set('Authorization',`Bearer ${writeToken}`).send({ name:'Bad',placement:'home',strategy:'collection',explanation:'Because' }).expect(400); });
  it('resolves the highest-priority scheduled rule with explicit stable product order', async () => {
    const create = (body: Record<string, unknown>) => supertest(app).post('/admin/recommendation-rules').set('Authorization',`Bearer ${writeToken}`).send({ name:'Homepage edit',placement:'home.featured',strategy:'manual',explanation:'Selected by our merchandising team',status:'active',startsAt:'2026-08-01T00:00:00.000Z',endsAt:'2026-10-01T00:00:00.000Z',...body });
    const rule = await create({ priority:50 }).expect(201); await create({ name:'Lower priority',priority:10 }).expect(201); await create({ name:'Future',priority:100,startsAt:'2026-10-01T00:00:00.000Z',endsAt:null }).expect(201);
    await supertest(app).put(`/admin/recommendation-rules/${(rule.body as { id:string }).id}/products`).set('Authorization',`Bearer ${writeToken}`).send({ productIds:[secondProduct,firstProduct] }).expect(200);
    const response = await supertest(app).get('/recommendations/home.featured?at=2026-08-30T00:00:00.000Z').expect(200); const body = response.body as { rule:{ priority:number }; products:Array<{ id:string;rank:number;explanation:string }> };
    expect(body.rule.priority).toBe(50); expect(body.products.map((item) => item.id)).toEqual([secondProduct,firstProduct]); expect(body.products.map((item) => item.rank)).toEqual([0,1]); expect(body.products[0]!.explanation).toBe('Selected by our merchandising team');
  });
  it('returns an explicit empty result when no placement rule is active', async () => { const response = await supertest(app).get('/recommendations/missing?at=2026-08-30T00:00:00.000Z').expect(200); expect(response.body as unknown).toEqual({ rule:null,products:[] }); });
  it('scores consented preferences with a deterministic explanation',async()=>{const db=getDatabase();await sql`UPDATE products SET audience='women',merchandising_priority=10 WHERE id=${firstProduct}`.execute(db);await sql`UPDATE products SET audience='men',merchandising_priority=100 WHERE id=${secondProduct}`.execute(db);await sql`INSERT INTO customer_preferences(user_id,audiences,category_ids,size_preferences,preferred_colours,personalization_consent,marketing_consent,created_at,updated_at) VALUES(${writeUserId},ARRAY['women'],ARRAY[]::uuid[],'{}'::jsonb,ARRAY[]::text[],true,false,now(),now()) ON CONFLICT(user_id) DO UPDATE SET audiences=ARRAY['women'],personalization_consent=true`.execute(db);await supertest(app).post('/admin/recommendation-rules').set('Authorization',`Bearer ${writeToken}`).send({name:'For you',placement:'account.for-you',strategy:'personalized',explanation:'Based on preferences',status:'active'}).expect(201);const first=await supertest(app).get('/account/recommendations/account.for-you').set('Authorization',`Bearer ${writeToken}`).expect(200);const second=await supertest(app).get('/account/recommendations/account.for-you').set('Authorization',`Bearer ${writeToken}`).expect(200);const firstBody=first.body as {products:Array<{id:string;score:number;explanation:string}>};const secondBody=second.body as {products:Array<{id:string;score:number}>};expect(firstBody.products[0]!.score).toBe(30);expect(firstBody.products[0]!.explanation).toContain('saved preferences');expect(firstBody.products.map((item)=>item.id)).toEqual(secondBody.products.map((item)=>item.id));});
  it('audits rule and product mutations', async () => { const rows = await getDatabase().selectFrom('audit_log').select('action').where('resource_type','=','recommendation_rule').execute(); expect(rows.map((row) => row.action)).toEqual(expect.arrayContaining(['recommendation_rule.create','recommendation_rule.products.replace'])); });
});
