import { sql } from 'kysely'; import { hashPassword } from './auth/password.js'; import { logger } from './config/logger.js'; import { createDatabase,destroyDatabase,getDatabase } from './db/database.js'; import { createPool } from './db/pool.js';
const categories=[['Men','men',null,'men',0],['Women','women',null,'women',1],['Kids','kids',null,'kids',2],['T-Shirts','men-t-shirts','men','men',0],['Polos','men-polos','men','men',1],['Kurtas','women-kurtas','women','women',0],['Dresses','women-dresses','women','women',1],['Kids Topwear','kids-topwear','kids','kids',0]] as const;
const products=[
  {name:'Indigo Block Print T-Shirt',slug:'indigo-block-print-t-shirt',category:'men-t-shirts',audience:'men',material:'100% cotton',fit:'Regular',badge:'Bestseller',priority:90,price:1299,sizes:['S','M','L','XL'],colour:'Indigo'},
  {name:'Classic Pique Polo',slug:'classic-pique-polo',category:'men-polos',audience:'men',material:'Cotton pique',fit:'Slim',badge:'New',priority:80,price:1699,sizes:['S','M','L','XL'],colour:'Forest Green'},
  {name:'Ivory Chanderi Kurta',slug:'ivory-chanderi-kurta',category:'women-kurtas',audience:'women',material:'Chanderi cotton',fit:'Straight',badge:'Festive Edit',priority:100,price:2899,sizes:['XS','S','M','L','XL'],colour:'Ivory'},
  {name:'Maroon Festive Kurta',slug:'maroon-festive-kurta',category:'women-kurtas',audience:'women',material:'Viscose silk',fit:'A-line',badge:'Puja Edit',priority:110,price:3299,sizes:['XS','S','M','L','XL'],colour:'Maroon'},
  {name:'Handloom Stripe Midi Dress',slug:'handloom-stripe-midi-dress',category:'women-dresses',audience:'women',material:'Handloom cotton',fit:'Relaxed',badge:'Limited',priority:75,price:2499,sizes:['XS','S','M','L'],colour:'Rust'},
  {name:'Kids Tiger Graphic Tee',slug:'kids-tiger-graphic-tee',category:'kids-topwear',audience:'kids',material:'Organic cotton',fit:'Regular',badge:'Popular',priority:70,price:799,sizes:['4Y','6Y','8Y','10Y'],colour:'Sunshine Yellow'},
] as const;
async function run(){createDatabase(createPool());const db=getDatabase();const categoryIds=new Map<string,string>();
  for(const [name,slug,parentSlug,audience,sortOrder] of categories){const parentId=parentSlug?categoryIds.get(parentSlug)??null:null;const row=await sql<{id:string}>`INSERT INTO categories(name,slug,parent_id,audience,sort_order,created_at,updated_at) VALUES(${name},${slug},${parentId},${audience},${sortOrder},now(),now()) ON CONFLICT(slug) DO UPDATE SET name=EXCLUDED.name,parent_id=EXCLUDED.parent_id,audience=EXCLUDED.audience,sort_order=EXCLUDED.sort_order,updated_at=now() RETURNING id`.execute(db);categoryIds.set(slug,row.rows[0]!.id);}
  const productIds=new Map<string,string>();for(const p of products){const categoryId=categoryIds.get(p.category)!;const row=await sql<{id:string}>`INSERT INTO products(name,slug,description,status,category_id,audience,material,fit,care_instructions,badge,merchandising_priority,created_at,updated_at) VALUES(${p.name},${p.slug},${`${p.material} ${p.fit.toLowerCase()} clothing designed for everyday Indian wardrobes.`},'active',${categoryId},${p.audience},${p.material},${p.fit},'Gentle machine wash; dry in shade',${p.badge},${p.priority},now(),now()) ON CONFLICT(slug) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description,status='active',category_id=EXCLUDED.category_id,audience=EXCLUDED.audience,material=EXCLUDED.material,fit=EXCLUDED.fit,care_instructions=EXCLUDED.care_instructions,badge=EXCLUDED.badge,merchandising_priority=EXCLUDED.merchandising_priority,updated_at=now() RETURNING id`.execute(db);const productId=row.rows[0]!.id;productIds.set(p.slug,productId);await sql`INSERT INTO product_categories(product_id,category_id,position) VALUES(${productId},${categoryId},0) ON CONFLICT(product_id,category_id) DO UPDATE SET position=0`.execute(db);await sql`INSERT INTO prices(product_id,amount,created_at,updated_at) VALUES(${productId},${p.price},now(),now()) ON CONFLICT(product_id) DO UPDATE SET amount=EXCLUDED.amount,updated_at=now()`.execute(db);await sql`INSERT INTO inventory(product_id,quantity,created_at,updated_at) VALUES(${productId},100,now(),now()) ON CONFLICT(product_id) DO UPDATE SET quantity=100,updated_at=now()`.execute(db);for(const size of p.sizes){const sku=`${p.slug.toUpperCase().replaceAll('-','_')}_${size}`;await sql`INSERT INTO product_variants(product_id,sku,size,colour_name,status,selling_price,mrp,quantity,low_stock_threshold,created_at,updated_at) VALUES(${productId},${sku},${size},${p.colour},'active',${p.price},${Math.round(p.price*1.2)},25,5,now(),now()) ON CONFLICT(sku) DO UPDATE SET product_id=EXCLUDED.product_id,size=EXCLUDED.size,colour_name=EXCLUDED.colour_name,status='active',selling_price=EXCLUDED.selling_price,mrp=EXCLUDED.mrp,quantity=25,updated_at=now()`.execute(db);}}
  const collection=await sql<{id:string}>`INSERT INTO merchandising_collections(name,slug,description,collection_type,status,priority,created_at,updated_at) VALUES('Durga Puja Edit','durga-puja-edit','Festive colour, craft and comfort','seasonal','active',100,now(),now()) ON CONFLICT(slug) DO UPDATE SET status='active',priority=100,updated_at=now() RETURNING id`.execute(db);const collectionId=collection.rows[0]!.id;await sql`DELETE FROM merchandising_collection_products WHERE collection_id=${collectionId}`.execute(db);const festive=['maroon-festive-kurta','ivory-chanderi-kurta','handloom-stripe-midi-dress'];for(const [position,slug] of festive.entries())await sql`INSERT INTO merchandising_collection_products(collection_id,product_id,position,created_at) VALUES(${collectionId},${productIds.get(slug)!},${position},now())`.execute(db);
  const campaign=await sql<{id:string}>`INSERT INTO merchandising_campaigns(name,slug,description,status,priority,created_at,updated_at) VALUES('Durga Puja','durga-puja','A seasonal celebration edit','active',100,now(),now()) ON CONFLICT(slug) DO UPDATE SET status='active',priority=100,updated_at=now() RETURNING id`.execute(db);await sql`INSERT INTO merchandising_campaign_collections(campaign_id,collection_id,position,created_at) VALUES(${campaign.rows[0]!.id},${collectionId},0,now()) ON CONFLICT(campaign_id,collection_id) DO UPDATE SET position=0`.execute(db);
  await sql`INSERT INTO promotions(name,code,description,discount_type,discount_value,collection_id,status,priority,created_at,updated_at) VALUES('Puja Welcome','PUJA15','15% on the festive edit','percentage',15,${collectionId},'active',50,now(),now()) ON CONFLICT(code) DO UPDATE SET status='active',discount_value=15,collection_id=EXCLUDED.collection_id,updated_at=now()`.execute(db);
  await sql`INSERT INTO merchandising_banners(name,placement,headline,body,desktop_image_url,mobile_image_url,alt_text,target_type,target_id,status,priority,created_at,updated_at) SELECT 'Puja Hero','home.hero','The Puja Edit','Crafted for every celebration','/demo/banners/puja-desktop.jpg','/demo/banners/puja-mobile.jpg','Models wearing the Durga Puja collection','collection',${collectionId},'active',100,now(),now() WHERE NOT EXISTS(SELECT 1 FROM merchandising_banners WHERE name='Puja Hero')`.execute(db);
  const layout=await sql<{id:string}>`INSERT INTO homepage_layouts(name,slug,status,priority,created_at,updated_at) VALUES('Festival Homepage','festival-homepage','active',100,now(),now()) ON CONFLICT(slug) DO UPDATE SET status='active',priority=100,updated_at=now() RETURNING id`.execute(db);await sql`DELETE FROM homepage_sections WHERE layout_id=${layout.rows[0]!.id}`.execute(db);await sql`INSERT INTO homepage_sections(layout_id,section_key,section_type,title,source_type,source_id,source_key,config,position,enabled,created_at,updated_at) VALUES(${layout.rows[0]!.id},'hero','hero',NULL,'banner_placement',NULL,'home.hero','{"autoplay":true}'::jsonb,0,true,now(),now()),(${layout.rows[0]!.id},'puja-edit','collection_grid','The Puja Edit','collection',${collectionId},NULL,'{}'::jsonb,1,true,now(),now())`.execute(db);
  const passwordHash=await hashPassword('MercuryDemo@2026');const users=[['admin@mercury.local','backend_admin','+919900000001'],['merchandiser@mercury.local','backend_write','+919900000002'],['viewer@mercury.local','backend_read','+919900000003'],['asha@mercury.local',null,'+919900000101'],['rahul@mercury.local',null,'+919900000102'],['maya@mercury.local',null,'+919900000103']] as const;for(const [email,role,mobile] of users){const u=await sql<{id:string}>`INSERT INTO users(email,password_hash,email_verified_at,mobile_number,mobile_verified_at,status,created_at,updated_at) VALUES(${email},${passwordHash},now(),${mobile},now(),'active',now(),now()) ON CONFLICT(email) DO UPDATE SET password_hash=EXCLUDED.password_hash,email_verified_at=now(),mobile_number=EXCLUDED.mobile_number,mobile_verified_at=now(),status='active',updated_at=now() RETURNING id`.execute(db);if(role)await sql`INSERT INTO user_roles(user_id,role_id,created_at) SELECT ${u.rows[0]!.id},id,now() FROM roles WHERE name=${role} ON CONFLICT DO NOTHING`.execute(db);}
  logger.info({products:products.length,users:users.length},'Demo seed complete');}
run().finally(async()=>{await destroyDatabase();}).catch((error:unknown)=>{logger.error({error},'Demo seed failed');process.exitCode=1;});
