import { getDatabase } from '../../db/database.js';
import { AppError } from '../../errors/AppError.js';

export interface AddressInput { label: string; recipientName: string; addressLine1: string; addressLine2?: string | null; city: string; state: string; postalCode: string; countryCode?: string; phone?: string | null; isDefault?: boolean }
export interface PreferenceInput { audiences?: string[]; categoryIds?: string[]; sizePreferences?: Record<string, string>; preferredColours?: string[]; personalizationConsent?: boolean; marketingConsent?: boolean }
export interface BehaviorInput { eventType: string; productId?: string | null; collectionId?: string | null; categoryId?: string | null; searchQuery?: string | null }
const audiences = ['men', 'women', 'kids', 'unisex']; const events = ['product_view', 'search', 'collection_view', 'wishlist_add', 'cart_add', 'purchase'];
const mapAddress = (r: { id: string; label: string; recipient_name: string; address_line1: string; address_line2: string | null; city: string; state: string; postal_code: string; country_code: string; phone: string | null; is_default: boolean; created_at: string; updated_at: string | undefined }) => ({ id: r.id, label: r.label, recipientName: r.recipient_name, addressLine1: r.address_line1, addressLine2: r.address_line2, city: r.city, state: r.state, postalCode: r.postal_code, countryCode: r.country_code, phone: r.phone, isDefault: r.is_default, createdAt: r.created_at, updatedAt: r.updated_at ?? r.created_at });
function validateAddress(input: AddressInput) { for (const key of ['label', 'recipientName', 'addressLine1', 'city', 'state', 'postalCode'] as const) if (!input[key]?.trim()) throw AppError.badRequest(`${key} is required`); if (input.countryCode !== undefined && !/^[A-Z]{2,3}$/.test(input.countryCode)) throw AppError.badRequest('invalid countryCode'); }
export async function listAddresses(userId: string) { return (await getDatabase().selectFrom('customer_addresses').selectAll().where('user_id', '=', userId).orderBy('is_default', 'desc').orderBy('created_at').orderBy('id').execute()).map(mapAddress); }
export async function createAddress(userId: string, input: AddressInput) { validateAddress(input); return getDatabase().transaction().execute(async (trx) => { if (input.isDefault) await trx.updateTable('customer_addresses').set({ is_default: false, updated_at: new Date().toISOString() }).where('user_id', '=', userId).execute(); const row = await trx.insertInto('customer_addresses').values({ user_id: userId, label: input.label.trim(), recipient_name: input.recipientName.trim(), address_line1: input.addressLine1.trim(), address_line2: input.addressLine2?.trim() ?? null, city: input.city.trim(), state: input.state.trim(), postal_code: input.postalCode.trim(), country_code: input.countryCode ?? 'IN', phone: input.phone?.trim() ?? null, is_default: input.isDefault ?? false, created_at: new Date().toISOString(), updated_at: new Date().toISOString() }).returningAll().executeTakeFirstOrThrow(); return mapAddress(row); }); }
export async function updateAddress(userId: string, id: string, input: Partial<AddressInput>) { const current = await getDatabase().selectFrom('customer_addresses').selectAll().where('id', '=', id).where('user_id', '=', userId).executeTakeFirst(); if (!current) throw AppError.notFound('Address not found'); const merged: AddressInput = { label: current.label, recipientName: current.recipient_name, addressLine1: current.address_line1, addressLine2: current.address_line2, city: current.city, state: current.state, postalCode: current.postal_code, countryCode: current.country_code, phone: current.phone, isDefault: current.is_default, ...input }; validateAddress(merged); return getDatabase().transaction().execute(async (trx) => { if (merged.isDefault) await trx.updateTable('customer_addresses').set({ is_default: false, updated_at: new Date().toISOString() }).where('user_id', '=', userId).execute(); const row = await trx.updateTable('customer_addresses').set({ label: merged.label.trim(), recipient_name: merged.recipientName.trim(), address_line1: merged.addressLine1.trim(), address_line2: merged.addressLine2?.trim() ?? null, city: merged.city.trim(), state: merged.state.trim(), postal_code: merged.postalCode.trim(), country_code: merged.countryCode ?? 'IN', phone: merged.phone?.trim() ?? null, is_default: merged.isDefault ?? false, updated_at: new Date().toISOString() }).where('id', '=', id).where('user_id', '=', userId).returningAll().executeTakeFirstOrThrow(); return mapAddress(row); }); }
export async function deleteAddress(userId: string, id: string) { const result = await getDatabase().deleteFrom('customer_addresses').where('id', '=', id).where('user_id', '=', userId).executeTakeFirst(); if (Number(result.numDeletedRows) === 0) throw AppError.notFound('Address not found'); }
const emptyPreferences = (userId: string) => ({ userId, audiences: [], categoryIds: [], sizePreferences: {}, preferredColours: [], personalizationConsent: false, marketingConsent: false });
export async function getPreferences(userId: string) { const r = await getDatabase().selectFrom('customer_preferences').selectAll().where('user_id', '=', userId).executeTakeFirst(); return r ? { userId: r.user_id, audiences: r.audiences, categoryIds: r.category_ids, sizePreferences: r.size_preferences, preferredColours: r.preferred_colours, personalizationConsent: r.personalization_consent, marketingConsent: r.marketing_consent } : emptyPreferences(userId); }
export async function updatePreferences(userId: string, input: PreferenceInput) { if (input.audiences && (input.audiences.some((a) => !audiences.includes(a)) || new Set(input.audiences).size !== input.audiences.length)) throw AppError.badRequest('invalid audiences'); if (input.categoryIds && new Set(input.categoryIds).size !== input.categoryIds.length) throw AppError.badRequest('categoryIds must be unique'); const current = await getPreferences(userId); const value = { ...current, ...input }; await getDatabase().insertInto('customer_preferences').values({ user_id: userId, audiences: value.audiences, category_ids: value.categoryIds, size_preferences: value.sizePreferences, preferred_colours: value.preferredColours, personalization_consent: value.personalizationConsent, marketing_consent: value.marketingConsent, created_at: new Date().toISOString(), updated_at: new Date().toISOString() }).onConflict((oc) => oc.column('user_id').doUpdateSet({ audiences: value.audiences, category_ids: value.categoryIds, size_preferences: value.sizePreferences, preferred_colours: value.preferredColours, personalization_consent: value.personalizationConsent, marketing_consent: value.marketingConsent, updated_at: new Date().toISOString() })).execute(); return getPreferences(userId); }
export async function recordBehavior(userId: string, input: BehaviorInput) { if (!events.includes(input.eventType)) throw AppError.badRequest('invalid eventType'); if (!input.productId && !input.collectionId && !input.categoryId && !input.searchQuery?.trim()) throw AppError.badRequest('an event subject is required'); const preferences = await getPreferences(userId); if (!preferences.personalizationConsent) throw AppError.forbidden('Personalization consent is required'); return (await getDatabase().insertInto('customer_behavior_events').values({ user_id: userId, event_type: input.eventType, product_id: input.productId ?? null, collection_id: input.collectionId ?? null, category_id: input.categoryId ?? null, search_query: input.searchQuery?.trim() ?? null, occurred_at: new Date().toISOString() }).returning(['id', 'event_type', 'occurred_at']).executeTakeFirstOrThrow()); }
